version: '3.8'

services:
  pulqatta-db:
    image: postgres:15-alpine
    container_name: pulqatta-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD:-1}
      POSTGRES_DB: pulqatta
    volumes:
      - pulqatta-db-data:/var/lib/postgresql/data
    ports:
      - "5433:5432" # Expose to host if you need to connect via DataGrip/pgAdmin (can be removed for prod security)
    restart: unless-stopped

  pulqatta-api:
    build: 
      context: .
      dockerfile: Dockerfile.api
    container_name: pulqatta-api
    depends_on:
      - pulqatta-db
    environment:
      - ConnectionStrings__DefaultConnection=Host=pulqatta-db;Port=5432;Database=pulqatta;Username=postgres;Password=${DB_PASSWORD:-1}
      - TelegramBotToken=${BOT_TOKEN}
    ports:
      - "5015:8080" # Maps container 8080 to host 5015
    restart: unless-stopped

  pulqatta-ui:
    build:
      context: .
      dockerfile: Dockerfile.ui
    container_name: pulqatta-ui
    ports:
      - "5044:80" # Maps container Nginx 80 to host 5044
    restart: unless-stopped

volumes:
  pulqatta-db-data:
