FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src

# Copy csproj and restore
COPY ["src/PulQatta.UI/PulQatta.UI.csproj", "PulQatta.UI/"]
RUN dotnet restore "PulQatta.UI/PulQatta.UI.csproj"

# Copy everything and build
COPY ["src/PulQatta.UI/", "PulQatta.UI/"]
WORKDIR "/src/PulQatta.UI"
RUN dotnet publish "PulQatta.UI.csproj" -c Release -o /app/publish

# Serve with Nginx
FROM nginx:alpine AS final
WORKDIR /usr/share/nginx/html
# Remove default nginx static assets
RUN rm -rf ./*
# Copy Blazor wasm output
COPY --from=build /app/publish/wwwroot .
# Copy custom nginx config to route traffic to index.html for SPA
COPY src/PulQatta.UI/nginx.conf /etc/nginx/nginx.conf
EXPOSE 80
